version: '3.9'

services:
  flask_app:
    build:
      context: ./Flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./Flask_app:/app
    restart: always

  django_app:
    build:
      context: ./Django_app
    ports:
      - "8000:8000"
    volumes:
      - ./Django_app:/app
    restart: always
